name: 定时运行程序并发布 Release

# 触发条件：每小时运行一次，且支持手动触发
on:
  schedule:
    - cron: '0 * * * *'  # 每小时的第0分钟运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-and-release:
    runs-on: windows-latest  # .NET 4.7.2 依赖 Windows 环境
    steps:
      # 步骤1：拉取仓库代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 步骤2：运行控制台程序（下载文件到 downloading 文件夹）
      - name: 运行下载程序
        run: |
          # 进入程序所在目录（根据实际路径调整，例如 ./ 或 ./bin/Release）
          cd .
          # 运行 exe（替换为你的程序文件名）
          .\NotepadPlusPlusReleaseDownloader.exe

      # 步骤3：创建 GitHub Release 并上传文件
      - name: 发布到 GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # Release 标题和标签（使用时间戳确保唯一）
          name: 自动更新-${{ github.run_number }}
          tag_name: auto-${{ github.run_number }}
          # 上传文件（根据实际情况调整路径，支持多个文件）
          files: |
            ./downloading/*
          # 自动删除旧的 Release（可选，避免仓库体积过大）
          # prerelease: true  # 标记为预发布（可选）
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的令牌，用于操作仓库
